# Generated by Django 3.2.12 on 2022-04-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lineno',
            new_name='linenos',
        ),
    ]
